### PR TITLE
[Performance] Reuse prebuilt chunk host metadata for Ascend chunk ops and earse synconize for qwen3.5 model

### PR DESCRIPTION
**Pull request by shaopeng-666**
### What this PR does / why we need it?
1.Erease the synconize before chunk o and chunk fwd h op.
2.decrease the time between 2 decode steps
3.refactor the gdn attention backend（delete the gdn attn builder patch）.
### Does this PR introduce _any_ user-facing change?
No
### How was this patch tested?
1.performence:
1)chunk o and chunk fwd h:
2)decode time between 2 decode steps decrease from 6ms to 3ms
3)3.5K/1.5K@TPOT50ms on Qwen3.5-397B-A13B model on A3:
330 performence: 2400 tokens/s @TPOT43ms
main code with this pr:2700 tokens/s @TPOT32ms
2.Accuracy:
Test GPQA on Qwen3.6-35B-A3B:
0 day accuracy:83.23.
main code with this pr:83.33

- vLLM version: v0.21.0
- vLLM main: https://github.com/vllm-project/vllm/commit/967c5c3bc38891f4465d3f4e99917ed837bb3833

### CODE REVIEW

File: vllm_ascend/patch/__init__.py [hunk 1]
```diff
@@ -326,19 +326,21 @@
 #           to override them, then delete the patch file `worker/patch_rejection_sampler.py`.
 #       2. make these functions as costom op, then remove AscendRejectionSampler
 #
-# ** 7. File: worker/patch_gdn_attn.py**
```
Comment (wangxiyuan) [inline vllm_ascend/patch/__init__.py:468]: rebase to main and remove this section directly

File: vllm_ascend/spec_decode/eagle_proposer.py [hunk 2]
```diff
@@ -619,13 +619,10 @@ def _propose(
...
                 )
                 # Keep the upstream-canonical mirror length-aligned with the
-                # padded subclass field, but only if the caller already
-                # populated it (production cm_base does; some unit-test mocks
-                # leave it None and assert it stays None). ``.clone()`` keeps
-                # the two fields independent so per-step in-place updates in
+                # padded subclass field. ``.clone()`` keeps the two fields
+                # independent so per-step in-place updates in
                 # ``attn_update_stack_num_spec_norm`` don't double-count.
-                if common_attn_metadata._seq_lens_cpu is not None:
```
Comment (wangxiyuan) [inline vllm_ascend/spec_decode/eagle_proposer.py]: @HF-001 please review this change. Thanks

**Comment by ZT-AIA** [comment]
@HF-001 This PR is related to your previous changes. Take a look and see if there are any issues.

**Comment by HF-001** [comment]
@ZT-AIA ok

File: vllm_ascend/worker/model_runner_v1.py [hunk 3]
```diff
@@ -916,16 +916,16 @@ def _prepare_inputs(
         # CPU values are optimistic (all drafts accepted). The kernel
         # corrects on GPU using the previous step's
         # valid_sampled_token_count_gpu. Otherwise, just copy from CPU.
+        cpu_values = self.input_batch.num_computed_tokens_cpu_tensor[:num_reqs].to(
```
Comment (HF-001) [inline vllm_ascend/worker/model_runner_v1.py]: @shaopeng-666 This operation should not be required in non asynchronous scheduling and speculative decoding scenarios？

File: vllm_ascend/spec_decode/eagle_proposer.py (hunk 2 above)
Comment (HF-001) [inline vllm_ascend/spec_decode/eagle_proposer.py]: @shaopeng-666 In non asynchronous scenarios, common_attd_metadata. _seq_lens_cpu is none. Is it possible to pass CI by changing it this way

File: vllm_ascend/worker/model_runner_v1.py (hunk 3 above)
Comment (shaopeng-666) [reply vllm_ascend/worker/model_runner_v1.py]: Yes,I will add a judgment condition of self.use_async_spec_decode for this logic.

**Comment by Clifton-yu** [comment]
330 performence  means what ?   I desire to know more details.

**Comment by shaopeng-666** [comment]
> 330 performence means what ? I desire to know more details.

It means the 0.18.0 version.

**Review by weijinqian0 — APPROVED** [review]

**Comment by OceanWang71** [comment]
Title
Metadata error when running Qwen3.6‑27B after installing vLLM at commit 9090368, but works fine on tag v0.20.2

Description
I am trying to validate PR #9310, which states its base as:

vLLM version: v0.20.2
vLLM main: vllm-project/vllm@9090368

I assumed that commit 9090368 is exactly the v0.20.2 snapshot. However, when I build and install vLLM from that commit, I encounter a metadata‑related error when loading a Qwen3.6‑27B model. The error goes away when I switch to the official v0.20.2 tag.

Steps to reproduce
Clone vLLM repository

bash
git clone https://github.com/vllm-project/vllm.git
cd vllm
Checkout commit 9090368

bash
git checkout 9090368
Install in editable mode

bash
pip install -e .
Try to serve a Qwen3.6‑27B model

bash
vllm serve Qwen/Qwen3.6-27B-Instruct
Observe the metadata error (service fails to start)

Expected behavior
The model should load successfully, just like it does when using tag v0.20.2.

Actual behavior
An exception is raised, indicating missing metadata fields or structure mismatch (e.g., 'XXX' object has no attribute 'non_spec_prefill_fallback_meta').

Environment
OS: Ubuntu 22.04.3 LTS (aarch64)

Python: 3.11.10

PyTorch: 2.10.0

Hardware: Ascend 910B (but the error might be platform‑independent)

Additional context
Commit 9090368 is explicitly mentioned as the base for PR #9310, but it appears to be different from the v0.20.2 tag – possibly a later snapshot.

This prevents proper testing of the PR. I would like to know the correct state of commit 9090368 & the correct version of vLLM or request a fix for the metadata compatibility issue.

Relevant logs
text
[Paste your error log here, e.g.:
RuntimeError: Expected attn_metadata.non_spec_prefill_fallback_meta.causal_conv1d for Ascend GDN fallback path.
]

File: vllm_ascend/worker/model_runner_v1.py [hunk 4]
```diff
@@ -1046,16 +1046,17 @@ def _prepare_inputs(
         # CPU values are optimistic (all drafts accepted). The kernel
         # corrects on GPU using the previous step's
         # valid_sampled_token_count_gpu. Otherwise, just copy from CPU.
+        if self.use_async_spec_decode:
+            cpu_values = self.input_batch.num_computed_tokens_cpu_tensor[:num_reqs].to(
```
Comment (zzzzwwjj) [inline vllm_ascend/worker/model_runner_v1.py]: `cpu_values` is unclear, pls modify variable name.

**Comment by shaopeng-666** [comment]
/e2e tests/e2e/pull_request/two_card/test_external_launcher.py
[Bot]: e2e command triggered. See [workflow run](https://github.com/vllm-project/vllm-ascend/actions/runs/27531100581) for details.
[Bot]: e2e command failed.

**Comment by maoxx241** [comment]
LGTM.

File: vllm_ascend/patch/worker/patch_qwen3_5.py [hunk 5]
```diff
@@ -150,6 +150,7 @@ def forward(
 Qwen3NextAttention.forward = AscendQwen3NextAttention.forward
 _GDN_PATCH_TARGET._split_ba_for_tp = AscendGatedDeltaNetAttention._split_ba_for_tp
 _GDN_PATCH_TARGET.get_state_shape = AscendGatedDeltaNetAttention.get_state_shape
+_GDN_PATCH_TARGET.get_attn_backend = AscendGatedDeltaNetAttention.get_attn_backend
```
Comment (wangxiyuan) [inline vllm_ascend/patch/worker/patch_qwen3_5.py:153]: @zzzzwwjj please notice that we should remove GDN patch totally, using GDN plugin instead

**Review by zzzzwwjj — APPROVED** [review]

**Comment by LoganJane** [comment]
LGTM.

**Review by LoganJane — APPROVED** [review]
