### ISSUE TITLE
[Bug]: recompute_scheduler + speculative decoding crashes with AttributeError: 'Request' object has no attribute 'async_tokens_to_discard' (both V1 and V2 runners)

### ISSUE THREAD

**Issue by xuchi-0808** [vllm-project/vllm-ascend#14871]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
PyTorch version: 2.10.0+cpu
OS: Ubuntu 24.04.4 LTS (aarch64)
Python version: 3.12.13
CPU: Kunpeng 920 7280Z (aarch64, 640 CPUs)
[pip3] torch_npu==2.10.0.post4
vLLM Version: 0.27.1
vLLM Ascend Version: 0.1.dev4715+g6e506867c (main @ dade7da62 + one unrelated feature commit; the offending line below is unchanged on main)
ASCEND_HOME_PATH=/usr/local/Ascend/cann-9.1.0
NPU: Atlas 800I A3 (Ascend 910_93), npu-smi 26.0.rc1
Docker image: quay.io/ascend/vllm-ascend:nightly-main-a3
```

</details>

### 🐛 Describe the bug

Any PD-disaggregated deployment that combines `recompute_scheduler_enable=true` on the decode node with speculative decoding (`deepseek_mtp`) crashes on the **first request**. The crash is identical on model runner V1 and V2. No lmhead TP / finegrained_tp_config involved.

The service starts and passes health checks (`GET /v1/models` returns 200); the first `POST /v1/chat/completions` returns an error response and all EngineCores die.

Reproduction — decode node on a single A3 box (16 chips), with a plain TP8 eager `kv_producer` prefill node running the same model on the other 8 chips (any model with an MTP head reproduces; a synthetic random-weight one also works, e.g. `luccafong/deepseek_mtp_main_random`):

```bash
vllm serve /path/to/model \
  --port 9002 \
  --data-parallel-size 8 \
  --max-num-batched-tokens 256 --max-num-seqs 16 \
  --enforce-eager \
  --speculative-config '{"method":"deepseek_mtp","num_speculative_tokens":1}' \
  --additional-config '{"recompute_scheduler_enable":true}' \
  --kv-transfer-config '{"kv_connector": "MooncakeConnectorV1", "kv_role": "kv_consumer", "kv_port": "30200", "engine_id": "2", "kv_connector_extra_config": {"prefill": {"dp_size": 1, "tp_size": 8}, "decode": {"dp_size": 8, "tp_size": 1}}}'
```

Full traceback of the first EngineCore (paths shortened; every DP rank shows the same):

```text
(EngineCore_DP0 pid=151) Traceback (most recent call last):
(EngineCore_DP0 pid=151)   File "vllm/v1/engine/core.py", line 1342, in run_engine_core
(EngineCore_DP0 pid=151)     engine_core.run_busy_loop()
(EngineCore_DP0 pid=151)   File "vllm/v1/fault_tolerance/engine_core_sentinel.py", line 179, in run_with_fault_tolerance
(EngineCore_DP0 pid=151)     busy_loop_func(self)
(EngineCore_DP0 pid=151)   File "vllm/v1/engine/core.py", line 2124, in run_busy_loop
(EngineCore_DP0 pid=151)     executed = self._process_engine_step()
(EngineCore_DP0 pid=151)   File "vllm/v1/engine/core.py", line 1439, in _process_engine_step
(EngineCore_DP0 pid=151)     outputs, model_executed = self.step_fn()
(EngineCore_DP0 pid=151)   File "vllm/v1/engine/core.py", line 711, in step_with_batch_queue
(EngineCore_DP0 pid=151)     engine_core_outputs = self.scheduler.update_from_output(
(EngineCore_DP0 pid=151)   File "vllm_ascend/core/recompute_scheduler.py", line 1088, in update_from_output
(EngineCore_DP0 pid=151)     and request.async_tokens_to_discard == 0
(EngineCore_DP0 pid=151) AttributeError: 'Request' object has no attribute 'async_tokens_to_discard'
```

Root cause: `recompute_scheduler.py:1088` (introduced in #12541) reads `request.async_tokens_to_discard`, but this attribute does not exist on the `Request` class of the paired vLLM (v0.27.1), nor on current vLLM main, and there is no definition/setattr/patch for it anywhere in vllm-ascend (this is the only read in the repo). Since `scheduled_spec_token_ids` is populated on every decode step of every spec-decode request (vllm/v1/core/sched/scheduler.py:731-739), the `and` chain always reaches the missing attribute — recompute + spec decoding cannot avoid it. The recompute scheduler is runner-agnostic core code, hence V1 and V2 behave identically (verified both: V2 single-box and V1 two-node 1P1D crash on the same line; with speculative decoding removed, the same topology serves traffic normally).

Impact: every recompute + speculative-decode combination on builds containing #12541, e.g. weekly DeepSeek_V3.1T_MTP1_PD-style decode configs (`recompute_scheduler_enable` + MTP).

Suggested direction: confirm where `async_tokens_to_discard` was supposed to come from (an upstream vLLM attribute the main2main sync anticipated, or a vllm-ascend-side patch that never landed). If it is not available in the paired vLLM, the condition should be removed or made defensive until the attribute actually exists.

**Comment by kunpengW-code** [comment]
@bowgneo recompute issue, PTAL

**Comment by bowgneo** [comment]
This issue has been fixed in https://github.com/vllm-project/vllm-ascend/issues/14871

**Comment by xuchi-0808** [comment]
This issue has been fixed by https://github.com/vllm-project/vllm-ascend/pull/14504
