### PR TITLE
[BugFix][SpecDecode] Avoid DSpark crash when causality API is absent

### PR DESCRIPTION
**Pull request by jianzs**
### What this PR does / why we need it?

PR #13531 added model-reported draft attention causality for GLM-5.2, but the
v1 Ascend DSpark proposer calls `get_draft_attn_causal()` unconditionally.
vLLM treats this model method as optional. Legacy non-causal DSpark models such
as DeepSeek V4 do not expose it, so DSpark initialization/warmup fails with:

```text
AttributeError: 'DSparkDeepseekV4ForCausalLM' object has no attribute 'get_draft_attn_causal'
```

This patch handles the optional capability directly in the attention metadata
path:

- use the model-reported value when `get_draft_attn_causal()` exists;
- otherwise preserve the previous non-causal DSpark behavior (`False`).

The unit tests cover both the missing-method fallback and an explicitly causal
model, so the GLM-5.2 behavior introduced by #13531 remains intact.

This is the main-branch counterpart of #13831. Refs #11126.

#### Duplicate check

Searched open PRs and issues for `get_draft_attn_causal`, `DSpark causality`,
and `DeepSeek V4 DSpark`.

- #13925 contains the same minimal runtime fallback but does not add regression
  coverage. Its author requested a main-branch PR from `jianzs` in #13926;
  this PR adds both missing-API and explicit-causal tests and is intended to
  supersede #13925 so only one implementation is merged.
- #11066 adds GLM-5.2 DSpark support and supplies model-specific causality; it
  does not cover models without the optional API.
- #12968 and #11126 track DeepSeek V4 DSpark model support, rather than this v1
  proposer interface regression.

### Does this PR introduce _any_ user-facing change?

Yes. DSpark models without `get_draft_attn_causal()` no longer crash and use
the legacy non-causal attention behavior. Models that explicitly report
causality are unchanged. There is no CLI or configuration change.

### How was this patch tested?

The fallback behavior is covered by unit tests for both a model without the
optional API and a model that explicitly reports causal attention. Changed-file
pre-commit, `py_compile`, and `git diff --check` passed during development.
Equivalent fallback behavior and the two regression paths were also validated
on the v0.26 integration branch on an Ascend dev0 node:

```bash
python3 -m pytest -q tests/ut/spec_decode/test_dspark_proposer.py
# 31 passed, 14 warnings
```

GitHub CI validates the current main head.

DeepSeek V4 Flash end-to-end evidence for that equivalent v0.26 fallback:

- TP=8, PP=1, DSpark: the server became ready; three short requests and one
  200-token request returned HTTP 200. Speculative-decoding metrics confirmed
  the DSpark path was active.
- TP=2, PP=4, DSpark, DSA-CP, KV producer (the original crash topology): the
  server became ready and three short requests returned HTTP 200 with the
  expected output. The original `AttributeError` and engine traceback did not
  recur.

The PP=4 direct KV-producer run also exposed an unrelated long-response content
anomaly. This PR's validation scope is the DSpark startup and optional-interface
compatibility regression; full long-output correctness remains separate.

No documentation update is needed because this restores compatibility without
changing configuration or public APIs.

- vLLM version: v0.26.0
- vLLM main: https://github.com/vllm-project/vllm/commit/0351e9aa1fdf1a51329d1906881528dfe61fc88e

---

<details>
<summary>Essential Elements of an Effective PR Description Checklist</summary>

- [x] The purpose of the PR.
- [x] The test plan.
- [x] The test results and end-to-end evaluation.
- [x] Documentation impact considered.

</details>

### CODE REVIEW

**Review by lilinsiman — APPROVED** [review]

File: vllm_ascend/spec_decode/dspark_proposer.py [hunk 1]
```diff
@@ -437,8 +437,11 @@ def set_inputs_first_pass(
         cad.max_seq_len = cad.max_seq_len + self.num_query_per_req
         cad.slot_mapping = self._per_group_query_slot_mapping_buffers[primary_gid][:num_query_total]
         cad.positions = self.positions  # this would be sliced in attention backend
-        # Currently, attention causality across draft layers are uniform.
-        cad.causal = self.model.get_draft_attn_causal()[0]
+        if hasattr(self.model, "get_draft_attn_causal"):
```
Comment (drslark) [inline vllm_ascend/spec_decode/dspark_proposer.py:440]: Good.

File: tests/ut/spec_decode/test_dspark_proposer.py [hunk 2]
```diff
@@ -81,11 +82,14 @@ def mock_parent_init(
             proposer.hidden_size = _HIDDEN_SIZE
             proposer.hidden_states = torch.empty(0)
             proposer._dflash_hidden_states = torch.empty(0)
-            proposer.model = SimpleNamespace(get_draft_attn_causal=lambda: [False])
+            proposer.model = (
```
Comment (drslark) [inline tests/ut/spec_decode/test_dspark_proposer.py:85]: Exactly.

**Review by drslark — APPROVED** [review]
LGTM.
Thanks for your efferts.

**Review by Tflowers-0129 — APPROVED** [review]

**Review by linfeng-yuan — APPROVED** [review]
