### PR TITLE
[BugFix][Offloader] Re-bind params to NZ static buffers after npu_format_cast

### PR DESCRIPTION
**Pull request by KINGFIOX**
### What this PR does / why we need it?

Follow-up bugfix for #11945 ("Support NZ static buffers for prefetch offload"), which had a bug in how the static buffers were cast to NZ format.

`torch_npu.npu_format_cast` returns a **new** tensor instead of modifying the buffer in place, so the NZ buffers stored back into `StaticBufferPool` by `_format_static_buffers_for_nz()` were never the tensors bound during `PrefetchOffloader.post_init()`: `param.data` and `_gpu_buffer` kept pointing at the pre-cast ND buffers, while the NZ buffers sat orphaned in the pool.

As a result, offloaded w8a8 weights were fed to NZ-only kernels (e.g. `npu_grouped_matmul_swiglu_quant`, `dispatch_ffn_combine`) in ND layout, causing a systematic logprob drift.

This PR:

- After casting the pool buffers to `ACL_FORMAT_FRACTAL_NZ`, re-binds NZ-marked params to the cast tensors and re-runs the initial prefetches (`start_onload_to_static()`), so the NZ buffers hold valid weights before the first forward.
- Hardens the e2e test `test_cpu_weight_offload`: the offload runner now generates `num_runs` (default 3) times inside one `VllmRunner`, and every run must match the no-offload baseline. This catches wrong-weights bugs that only show up after offload/reload cycles and would be missed by a single generate.

### Does this PR introduce _any_ user-facing change?

No API or configuration change. It fixes the accuracy of prefetch CPU offload (`--offload-backend prefetch`) with NZ-converted quantized weights (the default `VLLM_ASCEND_ENABLE_NZ=1` path): w8a8 models using prefetch offload now produce logprobs consistent with the no-offload baseline instead of a systematic drift.

### How was this patch tested?

- Updated e2e test: `tests/e2e/pull_request/one_card/test_cpu_weight_offload.py` (repeated-run logprob comparison against the no-offload baseline).
- Manual verification on GLM-5-w8a8, 2-node 16-card A3 (TP16/DP2, `weight_nz_mode=1`, fused_mc2 on), with `--offload-backend prefetch --offload-group-size 15 --offload-num-in-group 2 --offload-prefetch-step 2 --offload-params mlp`: greedy top-1 logprobs with offload moved back into the no-offload baseline range (e.g. `' red'`: -0.53~-0.65 before the fix, -0.85~-0.96 after, baseline -0.83~-0.92).
- CI on this PR.

- vLLM main: https://github.com/vllm-project/vllm/commit/ba07e4a48fc951300d97eb506217dd530583dea3

### CODE REVIEW

File: vllm_ascend/model_executor/offloader/prefetch.py [hunk 1]
```diff
@@ -126,7 +150,10 @@ def post_init(self):
             # No modules to offload
             return
 
-        _format_static_buffers_for_nz(self.buffer_pool, param_infos)
+        _format_static_buffers_for_nz(self.module_offloaders, self.buffer_pool, param_infos)
+
+        for i in range(min(self.prefetch_step, len(self.module_offloaders))):
+            self.module_offloaders[i].start_onload_to_static()
```
[the remark this answers is not in the document]
Comment (KINGFIOX) [reply vllm_ascend/model_executor/offloader/prefetch.py:190]: Thanks for the suggestion, but _is_onloaded does not exist — I grepped both upstream vLLM's _ModuleOffloader (vllm/model_executor/offloader/prefetch.py) and the Ascend subclass in this PR, and there is no such field anywhere.

File: tests/e2e/pull_request/one_card/test_cpu_weight_offload.py [hunk 2]
```diff
@@ -34,12 +34,16 @@ def _compare_offload_logprobs(
     prompts: list[str],
     atol: float = 0.0689,
     decode_atol: float | None = None,
+    num_runs: int = 3,
```
[the remark this answers is not in the document]
Comment (KINGFIOX) [reply tests/e2e/pull_request/one_card/test_cpu_weight_offload.py:37]: Good catch, fixed in 09c39a2eb (`[0, 1]` -> `[0, 2]`).

For a BF16 model like Qwen3-0.6B, `_should_trans_nz()` only converts BF16/FP16 weights to FRACTAL_NZ when `weight_nz_mode == 2` (the conversion happens in `AscendUnquantizedLinearMethod.process_weights_after_loading`), so the old `[0, 1]` parametrization silently ran the "NZ" case in ND.

Worth noting this is also exactly why this e2e test failed to catch the `npu_format_cast` re-binding bug introduced in #11945: the NZ static buffer path was never actually exercised. With `[0, 2]` it is.

**Comment by KINGFIOX** [comment]
### Known limitation: NZ weights + ACL graph capture

**1. Why NZ + graph does not work.**
When offloaded weights are NZ-formatted (`weight_nz_mode=1` for quantized weights, or `weight_nz_mode=2` also for BF16/FP16), their CPU-side storage stays in **ND** layout while the static NPU buffers are cast to `FRACTAL_NZ`. Every prefetch H2D copy (`gpu_buffer.copy_(cpu_storage)`) therefore requires an ND→NZ format conversion, which on current CANN is implemented as an **aclop** operator. aclop execution is rejected while an NPU graph capture is active:

```
RuntimeError: Cannot run aclop operators during NPU graph capture. Current working aclop is Identity
```

and the aborted capture then fails at `capture_end` with error 107025 (`capture model contains a stream that was not joined to the original stream`). So this combination dies during engine startup (capture phase), before producing any output. ND weights are unaffected: their prefetch copy is a plain H2D memcpy and is captured normally.

**2. How to triage failures under NZ + graph.**
Since this combination crashes at initialization, a failure observed with NZ + graph is by default this known init-time error, **not** an accuracy regression. When you see a failure with NZ + graph, first check where it failed:

- `RuntimeError` during engine startup / `capture_model` (e.g. `Engine core initialization failed`, the aclop error above, or 107025 capture errors) → the known limitation described in (1). The e2e case `test_prefetch_offload_accuracy[NZ-graph]` is marked `xfail(strict=True)` for this reason.
- Logprob / output mismatch while the engine runs fine (eager, or ND + graph) → a real accuracy issue, e.g. a wrong buffer binding like the one this PR fixes.

Offloader accuracy itself remains covered by `ND-eager`, `NZ-eager` and `ND-graph`. `NZ-graph` is expected to fail until the no-transdata prefetch path (CPU-side NZ byte image + raw storage copy) lands, at which point the `xfail` marker should be removed.

**Comment by KINGFIOX** [comment]
### Why the NZ + graph limitation does not block the intended offload scenario

Adding the usage-side context for the NZ + graph limitation described above:

**Weight offload targets prefill, and prefill runs eager.** Graph capture/replay is keyed to the captured batch sizes (`cudagraph_capture_sizes`, decode-sized); real prefill steps carry large, variable token counts and fall outside those sizes, so they take the eager (compiled-but-not-captured) path. In other words, the phase where offload matters is normally **not** executed under graph replay.

**Why prefill is the right phase for offload.** Prefill is **compute-bound**: each layer runs large GEMMs over hundreds/thousands of tokens, which leaves enough compute to hide the H2D weight prefetch — this overlap is exactly the design premise of the prefetch offloader (stream layer N+k's weights while layer N computes). Decode is the opposite regime: it is **weight-bandwidth-bound** (every step must touch all weights for a handful of tokens), so streaming weights from CPU would put H2D transfers on the critical path of every step and destroy decode latency. Offloading in decode is therefore not the goal.

**Consequence for triage.** The intended production combination for CPU weight offload is *prefill + eager* (with NZ weights this is the `NZ-eager` case, which passes). `NZ + graph` is an edge combination outside the primary usage — it stays covered by the `xfail(strict=True)` marker until the no-transdata prefetch path lands, and any failure there is the init-time capture crash, not an accuracy regression.

File: tests/e2e/pull_request/one_card/test_cpu_weight_offload.py [hunk 3]
```diff
@@ -55,35 +59,59 @@ def _compare_offload_logprobs(
...
+        pytest.param(False, 0, id="ND-graph"),
+        pytest.param(True, 2, id="NZ-eager"),
+        # TODO(wangfiox): nz+graph not supported yet
+        pytest.param(
+            False,
+            2,
+            id="NZ-graph",
+            marks=pytest.mark.xfail(
+                strict=True,
+                reason=(
```
Comment (kunpengW-code) [inline tests/e2e/pull_request/one_card/test_cpu_weight_offload.py:104]: A verification is added to inform users that the current feature does not support the graph mode.

**Comment by KINGFIOX** [comment]
### Update: fail-fast for NZ weights + ACL graph capture

`vllm_ascend/model_executor/offloader/prefetch.py` now **fails fast** on this unsupported combination: when any offloaded weight is stored as `FRACTAL_NZ` and graph capture is enabled (`enforce_eager=False`), `AscendPrefetchOffloader.post_init()` raises a clear `RuntimeError` **before any capture happens**, instead of letting EngineCore abort mid-capture with the opaque aclop / 107025 error.

**Review by yiz-liu — APPROVED** [review]

**Comment by KINGFIOX** [comment]
Hi @yiz-liu, gentle ping on this PR 🙂 It is approved and all CI checks (including the selected e2e tests on A2/310P) have passed. The review comments from @kunpengW-code have also been addressed in the latest commits. Could you help merge it when you have a chance? Thanks!
