### PR TITLE
[Main2Main][Deps][Misc] Upgrade vLLM to v0.15.0

### PR DESCRIPTION
**Pull request by wangxiyuan**
### What this PR does / why we need it?
This PR upgrades the vLLM dependency from `v0.14.1` to `v0.15.0`. This involves:
- Updating the `VLLM_TAG` in all `Dockerfile`.
- Updating the vLLM version in `docs/source/conf.py`.
- Removing conditional code paths specific to `v0.14.1` across the codebase, which simplifies maintenance.
- Fix `TypeError: MMEncoderAttention.__init__() got an unexpected keyword argument 'multimodal_config'` due to https://github.com/vllm-project/vllm/pull/31972.
- Fix `_shared_experts: 'NoneType' object is not callable` due to https://github.com/vllm-project/vllm/pull/32082 by https://github.com/vllm-project/vllm-ascend/pull/6335.
- Fix `ReshapeAndCacheOperation setup failed!` due to https://github.com/vllm-project/vllm/pull/25954 by overriding attention metadata slots.

This upgrade is necessary to keep the project aligned with the latest features, bug fixes, and API changes in the vLLM project.

### Does this PR introduce _any_ user-facing change?
No, this is an internal dependency update and does not introduce any user-facing changes.

### How was this patch tested?
CI is expected to pass with these changes, ensuring that all existing tests are successful with the new vLLM version.

- vLLM version: v0.14.1
- vLLM main: https://github.com/vllm-project/vllm/commit/dc917cceb877dfd13f98c538c4c96158047d98bd

co-authored-by: shen-shanshan <467638484@qq.com>

### CODE REVIEW

**Comment by wangxiyuan** [comment]
CI failed due to modelscope timeout. Not related to this PR.
