### PR TITLE
[BugFix][v0.26.0][SpecDecode] Avoid DSpark crash when causality API is absent

### PR DESCRIPTION
**Pull request by jianzs**
### What this PR does / why we need it?

PR #13531 added model-reported draft attention causality for GLM-5.2, but the
v1 Ascend DSpark proposer calls `get_draft_attn_causal()` unconditionally.
vLLM treats this model method as optional. Legacy non-causal DSpark models such
as DeepSeek V4 do not expose it, so DSpark initialization/warmup fails with:

```text
AttributeError: 'DSparkDeepseekV4ForCausalLM' object has no attribute 'get_draft_attn_causal'
```

This patch handles the optional capability directly in the attention metadata
path:

- use the model-reported value when `get_draft_attn_causal()` exists;
- otherwise preserve the previous non-causal DSpark behavior (`False`).

The unit tests cover both the missing-method fallback and an explicitly causal
model, so the GLM-5.2 behavior introduced by #13531 remains intact.

Related to #13531 and #11126.

#### Duplicate check

Searched open PRs and issues for `get_draft_attn_causal`, `DSpark causality`,
and `DeepSeek V4 DSpark`.

- #13926 contains the same minimal runtime fallback but does not add regression
  coverage. This PR predates it and tests both the missing-API and explicit
  causal paths.
- #11066 adds GLM-5.2 DSpark support and supplies model-specific causality; it
  does not cover models without the optional API.
- #12968 and #11126 track DeepSeek V4 DSpark model support, rather than this v1
  proposer interface regression.

### Does this PR introduce _any_ user-facing change?

Yes. DSpark models without `get_draft_attn_causal()` no longer crash and use
the legacy non-causal attention behavior. Models that explicitly report
causality are unchanged. There is no CLI or configuration change.

### How was this patch tested?

The fallback behavior is covered by unit tests for both a model without the
optional API and a model that explicitly reports causal attention. Changed-file
pre-commit, `py_compile`, and `git diff --check` passed during development, and
the equivalent fallback behavior was tested on an Ascend dev0 node:

```bash
python3 -m pytest -q tests/ut/spec_decode/test_dspark_proposer.py
# 31 passed, 14 warnings
```

GitHub CI validates the current head.

DeepSeek V4 Flash end-to-end evidence for that equivalent fallback behavior:

- TP=8, PP=1, DSpark: the server became ready; three short requests and one
  200-token request returned HTTP 200. Speculative-decoding metrics confirmed
  the DSpark path was active.
- TP=2, PP=4, DSpark, DSA-CP, KV producer (the original crash topology): the
  server became ready and three short requests returned HTTP 200 with the
  expected output. The original `AttributeError` and engine traceback did not
  recur.

The PP=4 direct KV-producer run also exposed an unrelated long-response content
anomaly. This PR's validation scope is the DSpark startup and optional-interface
compatibility regression; full long-output correctness remains separate.

No documentation update is needed because this restores compatibility without
changing configuration or public APIs.

---

<details>
<summary>Essential Elements of an Effective PR Description Checklist</summary>

- [x] The purpose of the PR.
- [x] The test plan.
- [x] The test results and end-to-end evaluation.
- [x] Documentation impact considered.

</details>

- vLLM version: v0.26.0
- vLLM main: https://github.com/vllm-project/vllm/commit/d02df748bf9efd99022f1a062597dc3cb3808485

### CODE REVIEW

File: tests/ut/spec_decode/test_dspark_proposer.py [hunk 1]
```diff
@@ -660,6 +666,20 @@ def test_cad_rewritten_to_cross_attention_shape(self):
         assert cad.actual_seq_lengths_q == [block_size] * num_reqs
         assert cad.decode_token_per_req == block_size
 
+    def test_cad_uses_model_reported_causality(self):
```
Comment (wangbj127) [inline tests/ut/spec_decode/test_dspark_proposer.py:667]: Good.

File: vllm_ascend/spec_decode/dspark_proposer.py [hunk 2]
```diff
@@ -122,6 +123,13 @@ def __init__(
         # per-layer context slot mappings as a flat list
         self._context_slot_mapping_buffers: list[torch.Tensor | None] | None = None
 
+    @staticmethod
+    def _resolve_draft_attn_causal(model: Any) -> bool:
```
Comment (wangbj127) [inline vllm_ascend/spec_decode/dspark_proposer.py]: Is it necessary to add a new method? I'm neutral.

File: vllm_ascend/spec_decode/dspark_proposer.py [hunk 3]
```diff
@@ -122,6 +123,13 @@ def __init__(
...
+        get_draft_attn_causal = getattr(model, "get_draft_attn_causal", None)
+        # Legacy DSpark models such as DeepSeek V4 use non-causal attention
+        # without exposing this optional vLLM model API.
+        return get_draft_attn_causal()[0] if get_draft_attn_causal is not None else False
```
[the remark this answers is not in the document]
Comment (jianzs) [reply vllm_ascend/spec_decode/dspark_proposer.py]: Updated.

File: vllm_ascend/spec_decode/dspark_proposer.py (hunk 2 above)
Comment (jianzs) [reply vllm_ascend/spec_decode/dspark_proposer.py]: Updated.

**Review by drslark — APPROVED** [review]
It's a mirror of https://github.com/vllm-project/vllm-ascend/pull/13935.
LGTM.

**Comment by wangbj127** [comment]
/rerun
[Bot]: rerun command failed: you do not have permission. Only the PR author or users with triage+ permission can trigger /rerun.

**Comment by lilinsiman** [comment]
/rerun
[Bot]: rerun completed.

**Failed:**
- E2E: still in progress, retry /rerun after completion

**Comment by jianzs** [comment]
/rerun
[Bot]: rerun completed.

**Failed:**
- E2E: still in progress, retry /rerun after completion
