### PR TITLE
[Misc][Main2Main] Upgrade vLLM to 0427

### PR DESCRIPTION
**Pull request by shen-shanshan**
### What this PR does / why we need it?
Based on https://github.com/vllm-project/vllm-ascend/pull/8856.

Sync to vLLM `4d51588e2381018348f1022dfa3a7698899805b7`.

Fix:

---

- MoE refactor @wxsIcey, introduced by https://github.com/vllm-project/vllm/pull/35782, https://github.com/vllm-project/vllm/pull/35949, https://github.com/vllm-project/vllm/pull/40560, https://github.com/vllm-project/vllm/pull/40671.
- `TypeError: rejection_sample() got an unexpected keyword argument 'synthetic_mode'` -> Add `synthetic_mode` and `synthetic_conditional_rates` param to ascend `rejection_sample()`.

---

| #  | Error                                              | Category  | Upstream Commit                                  | Affected vllm-ascend Path                                  | Fix                                              |
| :- | :------------------------------------------------- | :-------- | :----------------------------------------------- | :--------------------------------------------------------- | :----------------------------------------------- |
| 1  | `encoder_compilation_time` AttributeError          | Code Bug  | `c08f3b2a6` ([#39240](https://github.com/vllm-project/vllm/pull/39240)) | `worker/worker.py:567`                                     | `getattr` fallback                               |
| 2  | `AscendRMSNormGated activation` TypeError          | Code Bug  | `893611813` ([#40245](https://github.com/vllm-project/vllm/pull/40245)) | `ops/layernorm.py:160`, `_310p/ops/layernorm.py:43`        | Accept `activation` kwarg                        |
| 3  | `AscendFusedMoEMethod.apply topk_weights` TypeError| Code Bug  | many (e.g., `5e584ce9e` ([#35782](https://github.com/vllm-project/vllm/pull/35782)), `809d83c2d` ([#40560](https://github.com/vllm-project/vllm/pull/40560)), `4d51588e2` ([#40860](https://github.com/vllm-project/vllm/pull/40860))) | `ops/fused_moe/fused_moe.py:107`                         | Major refactor — follow-up PR                    |
| 4  | `_all_lora_classes` is tuple                       | Code Bug  | `a250f1bd5` ([#35077](https://github.com/vllm-project/vllm/pull/35077)) | `lora/utils.py:188`                                        | Rebuild tuple instead of `.add()`                |
| 5  | `ProfilingChunkScheduler hash_block_size` TypeError| Code Bug  | `7b1bc0a3e` ([#40946](https://github.com/vllm-project/vllm/pull/40946)) | `core/scheduler_profiling_chunk.py:57`                     | Forward new kwarg                                |
| 6  | `_moe_C.topk_softmax` AttributeError               | Code Bug  | MoE router refactor                              | router dispatch override needed                            | Provide `torch_npu` topk-softmax (with Issue 4)  |
| 7  | global experts shape mismatch                      | Code Bug  | follow-on of Issue 4                             | `quantization/methods/w8a8_dynamic.py:198`                 | Resolve once Issue 4 is fixed                    |

---

| # | Error | vLLM PR | Root Cause | Fix |
| :--- | :--- | :--- | :--- | :--- |
| 1 |  AssertionError: `assert common_attn_metadata.seq_lens_cpu_upper_bound is not None` | https://github.com/vllm-project/vllm/pull/40654  |  Upstream vLLM PR #40654 ("Avoid seq_lens_cpu GPU→CPU sync") added a new required field seq_lens_cpu_upper_bound to CommonAttentionMetadata. Several attention backends (including cross_attention.py) now assert this field is not None. vllm-ascend's AscendCommonAttentionMetadata subclass had 6 creation sites, none of which set this field. |  1. vllm_ascend/worker/model_runner_v1.py:2480 — Primary fix: added seq_lens_cpu_upper_bound=self.optimistic_seq_lens_cpu[:num_reqs_padded] to the main cm_base construction (matches upstream pattern where optimistic_seq_lens_cpu serves as the upper bound).<br>2. vllm_ascend/attention/utils.py:216 — Added propagation in unpadded() method so sliced copies preserve the field.<br>3. vllm_ascend/spec_decode/dflash_proposer.py:179 — Added seq_lens_cpu_upper_bound for DFlash proposer's graph-capture metadata.<br>4. vllm_ascend/spec_decode/eagle_proposer.py (3 locations): 422 — Graph-capture metadata for EAGLE proposer, 1583 — prepare_inputs() post-rejection metadata, 1662 — prepare_inputs_padded() metadata propagation.<br>5. vllm_ascend/worker/v2/attn_utils.py:99 — V2 attention utilities metadata construction. |
| 2 | Qwen3-MoE acc problem | #35782、#40560 | vLLM 的 MoE runner 重构（PR #35782、#40560）改变了 TP all-reduce 的调用路径，导致 Ascend 上 ALLTOALL/MC2 通信模式出现双重 TP all-reduce。<br>具体机制：<br>1. vLLM 旧代码：MoE runner 调用 layer.maybe_all_reduce_tensor_model_parallel()，AscendFusedMoE 覆写了该方法，对不同通信类型做正确判断（ALLTOALL/MC2 的 finalize() 已包含 TP 聚合，无需再 reduce）。<br>2. vLLM 新代码（升级后）：MoERunner.forward() 直接调用 vllm.distributed.tensor_model_parallel_all_reduce()，完全绕过了 Ascend 的覆写。<br>3. 在 Ascend A3 (910B) 上，默认 MoE 通信类型为 ALLTOALL/MC2/FUSED_MC2: moe_comm_method.finalize() 已包含 routed expert 的 TP all-reduce，_forward_shared_experts() 已对 shared expert 做 TP all-reduce（第 678 行），但 MoERunner.forward() 的 _maybe_reduce_final_output() 又做了一遍 TP all-reduce → 双重 reduce，输出被放大。<br>4. 在 Ascend A2 (910A) 上，默认通信类型为 AllGather：finalize() 不含 TP all-reduce，_forward_shared_experts() 跳过 TP all-reduce（条件判断不满足），_maybe_reduce_final_output() 做唯一的 TP all-reduce → 正确。 | 在 vllm_ascend/ops/fused_moe/fused_moe.py 的 AscendMoERunner 中新增两个覆写：<br>_fused_output_is_reduced property：当通信类型为 ALLTOALL/MC2/FUSED_MC2 时返回 True，告诉上游 MoERunner.forward() 不要再做 _maybe_reduce_final_output 的 TP all-reduce；<br>_maybe_reduce_shared_expert_output 方法：直接返回 shared_output（不做额外 reduce），因为 _forward_shared_experts 已处理。 |

### How was this patch tested?

- vLLM version: v0.19.1
- vLLM main: https://github.com/vllm-project/vllm/commit/d886c26d4d4fef7d079696beb4ece1cfb4b008a8

### CODE REVIEW

**Comment by shen-shanshan** [comment]
Full CI passed https://github.com/vllm-project/vllm-ascend/actions/runs/25532431248/job/74941359156?pr=8899

File: vllm_ascend/worker/worker.py [hunk 1]
```diff
@@ -553,10 +553,15 @@ def compile_or_warm_up_model(self):
         # Reset the seed to ensure that the random state is not affected by
         # the model initialization and profiling.
         set_random_seed(self.model_config.seed)
-
         return CompilationTimes(
             language_model=self.vllm_config.compilation_config.compilation_time,
-            encoder=self.compilation_config.encoder_compilation_time,
+            # `encoder_compilation_time` was added after v0.19.1 (vLLM #39240); fall
```
Comment (wangxiyuan) [inline vllm_ascend/worker/worker.py:558]: revert this change

File: vllm_ascend/__init__.py [hunk 2]
```diff
@@ -15,6 +15,25 @@
 # This file is a part of the vllm-ascend project.
 #
 
+_GLOBAL_PATCH_APPLIED = False
+
+
+def _ensure_global_patch():
```
Comment (wangxiyuan) [inline vllm_ascend/__init__.py:21]: change to  the correct patch way.

**Review by wangxiyuan — APPROVED** [review]
