### ISSUE TITLE
[Bug]: When using vLLM DP to Deploy Qwen3-32B, meet AscendAttentionMetadataBuilder.build() got an unexpected keyword argument 'max_num_tokens_across_dp''

### ISSUE THREAD

**Issue by ghy-cmd** [vllm-project/vllm-ascend#2576]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
INFO 08-27 09:23:20 [importing.py:17] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 08-27 09:23:20 [importing.py:29] Triton is not installed. Using dummy decorators. Install it via `pip install triton` to enable kernel compilation.
INFO 08-27 09:23:21 [__init__.py:39] Available plugins for group vllm.platform_plugins:
INFO 08-27 09:23:21 [__init__.py:41] - ascend -> vllm_ascend:register
INFO 08-27 09:23:21 [__init__.py:44] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 08-27 09:23:21 [__init__.py:235] Platform plugin ascend is activated
WARNING 08-27 09:23:25 [_custom_ops.py:22] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
Collecting environment information...
PyTorch version: 2.5.1
Is debug build: False

OS: openEuler 22.03 (LTS-SP4) (aarch64)
GCC version: (GCC) 10.3.1
Clang version: Could not collect
CMake version: version 4.0.3
Libc version: glibc-2.34

Python version: 3.10.17 (main, May  8 2025, 08:13:48) [GCC 10.3.1] (64-bit runtime)
Python platform: Linux-6.6.0-28.0.0.34.oe2403.aarch64-aarch64-with-glibc2.34

CPU:
Architecture:                         aarch64
CPU op-mode(s):                       64-bit
Byte Order:                           Little Endian
CPU(s):                               192
On-line CPU(s) list:                  0-191
Vendor ID:                            HiSilicon
BIOS Vendor ID:                       HiSilicon
Model name:                           Kunpeng-920
BIOS Model name:                      HUAWEI Kunpeng 920 5250
Model:                                0
Thread(s) per core:                   1
Core(s) per socket:                   48
Socket(s):                            4
Stepping:                             0x1
BogoMIPS:                             200.00
Flags:                                fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                            12 MiB (192 instances)
L1i cache:                            12 MiB (192 instances)
L2 cache:                             96 MiB (192 instances)
L3 cache:                             192 MiB (8 instances)
NUMA node(s):                         8
NUMA node0 CPU(s):                    0-23
NUMA node1 CPU(s):                    24-47
NUMA node2 CPU(s):                    48-71
NUMA node3 CPU(s):                    72-95
NUMA node4 CPU(s):                    96-119
NUMA node5 CPU(s):                    120-143
NUMA node6 CPU(s):                    144-167
NUMA node7 CPU(s):                    168-191
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; __user pointer sanitization
Vulnerability Spectre v2:             Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.0.0
[pip3] torch==2.5.1
[pip3] torch-npu==2.5.1.post1.dev20250528
[pip3] torchvision==0.20.1
[pip3] transformers==4.52.4
[conda] Could not collect
vLLM Version: 0.9.1
vLLM Ascend Version: 0.9.1rc1

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_TILING_SIZE=10240
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=0
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:
ASCEND_AICPU_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_OPSRUNNER_KERNEL_CACHE_TYPE=3
ATB_RUNNER_POOL_SIZE=64
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_LAUNCH_KERNEL_WITH_TILING=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 25.2.0                   Version: 25.2.0                                               |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B3               | OK            | 101.8       40                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          3394 / 65536         |
+===========================+===============+====================================================+
| 1     910B3               | OK            | 100.1       39                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          3394 / 65536         |
+===========================+===============+====================================================+
| 2     910B3               | OK            | 99.1        40                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3395 / 65536         |
+===========================+===============+====================================================+
| 3     910B3               | OK            | 98.2        40                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          3393 / 65536         |
+===========================+===============+====================================================+
| 4     910B3               | OK            | 96.3        45                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          3394 / 65536         |
+===========================+===============+====================================================+
| 5     910B3               | OK            | 93.1        44                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          3393 / 65536         |
+===========================+===============+====================================================+
| 6     910B3               | OK            | 95.1        43                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          3394 / 65536         |
+===========================+===============+====================================================+
| 7     910B3               | OK            | 96.8        46                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          3394 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 0                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.1.RC1
innerversion=V100R001C21SPC001B238
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21]
arch=aarch64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.1.RC1/aarch64-linux
```

</details>

### 🐛 Describe the bug

Node 0：
``` bash
#!/bin/sh

# this obtained through ifconfig
# nic_name is the network interface name corresponding to local_ip
nic_name="enp189s0f0"
local_ip="76.69.21.202"

export VLLM_USE_MODELSCOPE=True
export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=100
export VLLM_USE_V1=1
export HCCL_BUFFSIZE=1024

# The w8a8 weight can obtained from https://www.modelscope.cn/models/vllm-ascend/DeepSeek-V3.1-W8A8
# If you want to the quantization manually, please refer to https://vllm-ascend.readthedocs.io/en/latest/user_guide/feature_guide/quantization.html
vllm serve /llm/Qwen3-32B \
--host 0.0.0.0 \
--port 8004 \
--data-parallel-size 4 \
--data-parallel-size-local 2 \
--data-parallel-address $local_ip \
--data-parallel-rpc-port 13389 \
--tensor-parallel-size 4 \
--seed 1024 \
--served-model-name Qwen3-32B \
--max-num-seqs 16 \
--max-model-len 32768 \
--max-num-batched-tokens 32768 \
--trust-remote-code \
--no-enable-prefix-caching \
--gpu-memory-utilization 0.9 \
--additional-config '{"ascend_scheduler_config":{"enabled":true}}'
```

Node1:
```bash
#!/bin/sh

nic_name="enp189s0f0"
local_ip="76.69.21.203"

export VLLM_USE_MODELSCOPE=True
export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=100
export VLLM_USE_V1=1
export HCCL_BUFFSIZE=1024

vllm serve /llm/Qwen3-32B \
--host 0.0.0.0 \
--port 8004 \
--headless \
--data-parallel-size 4 \
--data-parallel-size-local 2 \
--data-parallel-start-rank 2 \
--data-parallel-address 76.69.21.202 \
--data-parallel-rpc-port 13389 \
--tensor-parallel-size 4 \
--seed 1024 \
--served-model-name Qwen3-32B \
--max-num-seqs 16 \
--max-model-len 32768 \
--max-num-batched-tokens 32768 \
--trust-remote-code \
--no-enable-prefix-caching \
--gpu-memory-utilization 0.92 \
--additional-config '{"ascend_scheduler_config":{"enabled":true}}'
# --enable-expert-parallel \
```

The deploy shell is above. It can load model successfully, but when sending requests, it reports:
```
AscendAttentionMetadataBuilder.build() got an unexpected keyword argument 'max_num_tokens_across_dp''
```

**Comment by ghy-cmd** [comment]
Add full ERROR report:
```
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [dump_input.py:69] Dumping input data
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [dump_input.py:71] V1 LLM engine (v0.9.1) with config: model='/llm/Qwen3-32B', speculative_config=None, tokenizer='/llm/Qwen3-32B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=npu, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=1024, served_model_name=Qwen3-32B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["all"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.unified_ascend_attention_with_output","vllm.unified_ascend_attention_with_output"],"use_inductor":false,"compile_sizes":[],"inductor_compile_config":{},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,384,248,112,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}, 
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [dump_input.py:79] Dumping scheduler output for model execution:
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [dump_input.py:80] SchedulerOutput(scheduled_new_reqs=[NewRequestData(req_id=cmpl-8d338c46f3224fc0bd3083492386d808-0,prompt_token_ids_len=5,mm_inputs=[],mm_hashes=[],mm_positions=[],sampling_params=SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=0, min_p=0.0, seed=None, stop=[], stop_token_ids=[151643], bad_words=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=50, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None, guided_decoding=None, extra_args=None),block_ids=([1],),num_computed_tokens=0,lora_request=None)], scheduled_cached_reqs=[], num_scheduled_tokens={cmpl-8d338c46f3224fc0bd3083492386d808-0: 5}, total_num_scheduled_tokens=5, scheduled_spec_decode_tokens={}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[1], finished_req_ids=[], free_encoder_input_ids=[], structured_output_request_ids={}, grammar_bitmask=null, kv_connector_metadata=null)
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [dump_input.py:82] SchedulerStats(num_running_reqs=1, num_waiting_reqs=0, gpu_cache_usage=0.00042946102641183703, prefix_cache_stats=PrefixCacheStats(reset=False, requests=0, queries=0, hits=0), spec_decoding_stats=None)
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517] EngineCore encountered a fatal error.
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517] Traceback (most recent call last):
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 508, in run_engine_core
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]     engine_core.run_busy_loop()
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 858, in run_busy_loop
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]     executed = self._process_engine_step()
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 560, in _process_engine_step
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]     outputs, model_executed = self.step_fn()
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 231, in step
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]     model_output = self.execute_model(scheduler_output)
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 217, in execute_model
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]     raise err
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 211, in execute_model
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]     return self.model_executor.execute_model(scheduler_output)
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 163, in execute_model
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]     (output, ) = self.collective_rpc("execute_model",
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 220, in collective_rpc
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]     result = get_response(w, dequeue_timeout)
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 207, in get_response
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517]     raise RuntimeError(
(EngineCore_0 pid=25225) ERROR 08-27 09:52:26 [core.py:517] RuntimeError: Worker failed with error 'AscendAttentionMetadataBuilder.build() got an unexpected keyword argument 'max_num_tokens_across_dp'', please check the stack trace above for the root cause
```

**Comment by ghy-cmd** [comment]
After updating vllm-ascend from version 0.9.1RC1 to 0.9.1RC3, this error no longer occurs.
